version: '3.8'

services:
  hades-arango:
    image: arangodb:3.11
    environment:
      - ARANGO_ROOT_PASSWORD=olympus
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps:/var/lib/arangodb3-apps
    networks:
      - olympus-net
      - ladon_network
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8529"

  hades-rag:
    build:
      context: ./hades
      dockerfile: Dockerfile
    environment:
      - ARANGO_HOST=hades-arango
      - ARANGO_PORT=8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=olympus
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "8001:8001"
    volumes:
      - ./hades:/app
      - ./.cache:/app/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - hades-arango
    networks:
      - olympus-net
      - ladon_network
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8001"

networks:
  olympus-net:
    driver: bridge
  ladon_network:
    external: true

volumes:
  arango_data:
  arango_apps:
