server:
  http_listen_port: 9907
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:9906/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            log: log
            stream: stream
            service: attrs.service
            level: attrs.level
      - labels:
          stream:
          service:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log

  # HADES application logs
  - job_name: hades-rag
    static_configs:
      - targets:
          - localhost
        labels:
          job: hades
          service: rag
          __path__: /var/log/hades/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            component: component
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:
      - output:
          source: message

  # ArangoDB logs
  - job_name: hades-arango
    static_configs:
      - targets:
          - localhost
        labels:
          job: hades
          service: arango
          __path__: /var/log/arangodb3/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+) \[(?P<level>\w+)\] (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          level:
      - output:
          source: message

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/{syslog,messages,*.log}
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<host>\S+)\s+(?P<application>\S+)(?:\[(?P<pid>\d+)\])?:\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 'Jan 02 15:04:05'
      - labels:
          host:
          application:
          pid:
      - output:
          source: message

  # LadonStack infrastructure logs
  - job_name: ladon
    static_configs:
      - targets:
          - localhost
        labels:
          job: ladon
          __path__: /var/log/ladon/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: ts
            level: level
            message: msg
            component: component
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:
      - output:
          source: message
