groups:
  - name: hardware
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: Memory usage is above 85% for 5 minutes

      - alert: HighGPUUsage
        expr: DCGM_FI_DEV_GPU_UTIL > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High GPU usage on GPU {{ $labels.gpu_id }}
          description: GPU utilization is above 90% for 5 minutes

      - alert: HighGPUTemperature
        expr: DCGM_FI_DEV_GPU_TEMP > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High GPU temperature on GPU {{ $labels.gpu_id }}
          description: GPU temperature is above 80°C for 2 minutes

      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Disk space running out on {{ $labels.instance }}
          description: Disk usage is above 85% for 5 minutes

  - name: network
    rules:
      - alert: NetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) > 0 or rate(node_network_transmit_errs_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Network errors detected on {{ $labels.instance }}
          description: Network interface {{ $labels.device }} is showing errors

      - alert: UnusualNetworkThroughput
        expr: rate(node_network_receive_bytes_total[5m]) > 1e8 or rate(node_network_transmit_bytes_total[5m]) > 1e8
        for: 5m
        labels:
          severity: info
        annotations:
          summary: Unusual network activity on {{ $labels.instance }}
          description: Network throughput is above 100MB/s for 5 minutes
